var data=[
    {id:0,
    title:'新列表1',
    todo:[{t:'中午风格风格',done:false},{t:'的发生事故',done:true},{t:'发射点发射点风格',done:false}],
    color:'#C76FDE'},
    {id:1,
    title:'新列表2',
    todo:[{t:'广泛豆腐干大概的',done:false}],
    color:'#54C727'},
    {id:2,
    title:'新列表3',
    todo:[{t:'经济搞好经济是否读过',done:true}],
    color:'#4AACFA'},
];
var colors=[
    '#C76FDE','#54C727','#4AACFA','#F0C804','#9D835C','#F5285F','#F39403'
];
var app=angular.module('app',[]);
    app.controller('ctr',function($scope){
    	$scope.data=data;
    	$scope.colors=colors;
        $scope.index=0;
        $scope.flag=false;
        $scope.flag1=false;
        $scope.flag2=true;
        $scope.select=function(i){
        	$scope.index=i;
        }
        $scope.add=function(){
        	if($scope.data.length==0){
        	    $scope.data.push({id:0,title:'新列表1',todo:[],color:colors[$scope.data.length%7]});
                $scope.index=0;
        	}else{
        		var i=$scope.data.length-1;
        	    $scope.data.push({id:$scope.data[i].id+1,title:'新列表'+($scope.data[i].id+2),todo:[],color:colors[$scope.data.length%7]});
                $scope.index=$scope.data.length-1;
        	}        	
        }
        
        $scope.dianji=function(){
            $scope.flag=!$scope.flag;
            $scope.title=$scope.data[$scope.index].title;
            $scope.color=$scope.data[$scope.index].color;
        }
        $scope.wancheng=function(){
            $scope.flag=!$scope.flag;
            $scope.data[$scope.index].title=$scope.title;
            $scope.data[$scope.index].color=$scope.color;
        }
        $scope.del=function(){
        	$scope.flag=!$scope.flag;
        	$scope.data.splice($scope.index,1);
        	$scope.index=0;
        }
        $scope.huanys=function(v){
            $scope.color=v;
        }
        $scope.xsyc=function(){
            $scope.flag1=!$scope.flag1;
        }
        $scope.xsyc1=function(){
            $scope.flag2=!$scope.flag2;
        }
        $scope.xxm=function(){
        	$scope.data[$scope.index].todo.push({t:'.',done:false});
        }
        $scope.dqq=function(v){
        	v.done=!v.done;
        }
        $scope.kbj=function(v,e){
        	v.t=e.target.innerText;
        }
});